# Generated by Django 3.1.4 on 2020-12-19 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(related_name='_customuser_followers_+', through='users.UsersRelation', to=settings.AUTH_USER_MODEL, verbose_name='フォローされているユーザー'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followings',
            field=models.ManyToManyField(related_name='_customuser_followings_+', through='users.UsersRelation', to=settings.AUTH_USER_MODEL, verbose_name='フォロー中のユーザー'),
        ),
    ]
